export function sampleAssets() {
  return [
    {
      id: 'test-asset-1',
      type: 'asset',
      name: 'Chase Checking',
      categoryId: 'cat-cash',
      value: 5000,
      currency: 'USD',
      tags: ['emergency-fund'],
      notes: 'Primary checking',
      isStock: false,
      ticker: null,
      shares: null,
      pricePerShare: null,
      lastPriceUpdate: null,
      createdAt: '2025-01-15T10:00:00.000Z',
      updatedAt: '2025-03-01T10:00:00.000Z',
    },
    {
      id: 'test-asset-2',
      type: 'asset',
      name: 'Vanguard S&P 500',
      categoryId: 'cat-stocks',
      value: 25000,
      currency: 'USD',
      tags: ['retirement', 'index-fund'],
      notes: '',
      isStock: true,
      ticker: 'VOO',
      shares: 50,
      pricePerShare: 500,
      lastPriceUpdate: '2025-03-01T10:00:00.000Z',
      createdAt: '2025-01-10T10:00:00.000Z',
      updatedAt: '2025-03-01T10:00:00.000Z',
    },
    {
      id: 'test-asset-3',
      type: 'asset',
      name: 'Downtown Apartment',
      categoryId: 'cat-real-estate',
      value: 350000,
      currency: 'USD',
      tags: ['property'],
      notes: 'Primary residence',
      isStock: false,
      ticker: null,
      shares: null,
      pricePerShare: null,
      lastPriceUpdate: null,
      createdAt: '2025-01-05T10:00:00.000Z',
      updatedAt: '2025-02-15T10:00:00.000Z',
    },
    {
      id: 'test-asset-4',
      type: 'asset',
      name: 'London Savings',
      categoryId: 'cat-savings',
      value: 10000,
      currency: 'GBP',
      tags: [],
      notes: 'UK savings account',
      isStock: false,
      ticker: null,
      shares: null,
      pricePerShare: null,
      lastPriceUpdate: null,
      createdAt: '2025-02-01T10:00:00.000Z',
      updatedAt: '2025-03-10T10:00:00.000Z',
    },
  ]
}

export function sampleLiabilities() {
  return [
    {
      id: 'test-liab-1',
      type: 'liability',
      name: 'Visa Credit Card',
      categoryId: 'cat-credit-cards',
      value: 3200,
      currency: 'USD',
      tags: ['monthly'],
      notes: '',
      isStock: false,
      ticker: null,
      shares: null,
      pricePerShare: null,
      lastPriceUpdate: null,
      createdAt: '2025-01-20T10:00:00.000Z',
      updatedAt: '2025-03-05T10:00:00.000Z',
    },
    {
      id: 'test-liab-2',
      type: 'liability',
      name: 'Home Mortgage',
      categoryId: 'cat-mortgage',
      value: 280000,
      currency: 'USD',
      tags: ['property'],
      notes: '30-year fixed',
      isStock: false,
      ticker: null,
      shares: null,
      pricePerShare: null,
      lastPriceUpdate: null,
      createdAt: '2025-01-05T10:00:00.000Z',
      updatedAt: '2025-02-15T10:00:00.000Z',
    },
  ]
}

export function sampleExchangeRates() {
  return { GBP: 0.79, EUR: 0.92, INR: 83.5 }
}

export function sampleSnapshots() {
  return [
    {
      id: 'test-snap-1',
      date: '2025-01-01',
      baseCurrency: 'USD',
      totalAssets: 370000,
      totalLiabilities: 283200,
      netWorth: 86800,
      breakdown: [
        { categoryId: 'cat-cash', name: 'Cash & Checking', total: 5000, type: 'asset' },
        { categoryId: 'cat-stocks', name: 'Stocks', total: 20000, type: 'asset' },
        { categoryId: 'cat-real-estate', name: 'Real Estate', total: 345000, type: 'asset' },
        { categoryId: 'cat-credit-cards', name: 'Credit Cards', total: 3200, type: 'liability' },
        { categoryId: 'cat-mortgage', name: 'Mortgage', total: 280000, type: 'liability' },
      ],
      items: [],
      createdAt: '2025-01-01T12:00:00.000Z',
    },
    {
      id: 'test-snap-2',
      date: '2025-02-01',
      baseCurrency: 'USD',
      totalAssets: 380000,
      totalLiabilities: 282000,
      netWorth: 98000,
      breakdown: [
        { categoryId: 'cat-cash', name: 'Cash & Checking', total: 5000, type: 'asset' },
        { categoryId: 'cat-stocks', name: 'Stocks', total: 25000, type: 'asset' },
        { categoryId: 'cat-real-estate', name: 'Real Estate', total: 350000, type: 'asset' },
        { categoryId: 'cat-credit-cards', name: 'Credit Cards', total: 2000, type: 'liability' },
        { categoryId: 'cat-mortgage', name: 'Mortgage', total: 280000, type: 'liability' },
      ],
      items: [],
      createdAt: '2025-02-01T12:00:00.000Z',
    },
    {
      id: 'test-snap-3',
      date: '2025-03-01',
      baseCurrency: 'USD',
      totalAssets: 392658,
      totalLiabilities: 283200,
      netWorth: 109458,
      breakdown: [
        { categoryId: 'cat-cash', name: 'Cash & Checking', total: 5000, type: 'asset' },
        { categoryId: 'cat-stocks', name: 'Stocks', total: 25000, type: 'asset' },
        { categoryId: 'cat-real-estate', name: 'Real Estate', total: 350000, type: 'asset' },
        { categoryId: 'cat-savings', name: 'Savings', total: 12658, type: 'asset' },
        { categoryId: 'cat-credit-cards', name: 'Credit Cards', total: 3200, type: 'liability' },
        { categoryId: 'cat-mortgage', name: 'Mortgage', total: 280000, type: 'liability' },
      ],
      items: [],
      createdAt: '2025-03-01T12:00:00.000Z',
    },
  ]
}

export const DEFAULT_CATEGORIES = [
  { id: 'cat-cash', name: 'Cash & Checking', type: 'asset', icon: 'banknotes', color: '#22c55e', isDefault: true },
  { id: 'cat-savings', name: 'Savings', type: 'asset', icon: 'piggy-bank', color: '#10b981', isDefault: true },
  { id: 'cat-investments', name: 'Investments', type: 'asset', icon: 'chart', color: '#6366f1', isDefault: true },
  { id: 'cat-retirement', name: 'Retirement', type: 'asset', icon: 'shield', color: '#8b5cf6', isDefault: true },
  { id: 'cat-real-estate', name: 'Real Estate', type: 'asset', icon: 'home', color: '#f59e0b', isDefault: true },
  { id: 'cat-crypto', name: 'Crypto', type: 'asset', icon: 'bolt', color: '#f97316', isDefault: true },
  { id: 'cat-stocks', name: 'Stocks', type: 'asset', icon: 'chart-bar', color: '#3b82f6', isDefault: true },
  { id: 'cat-vehicles', name: 'Vehicles', type: 'asset', icon: 'car', color: '#06b6d4', isDefault: true },
  { id: 'cat-other-assets', name: 'Other Assets', type: 'asset', icon: 'box', color: '#64748b', isDefault: true },
  { id: 'cat-credit-cards', name: 'Credit Cards', type: 'liability', icon: 'card', color: '#ef4444', isDefault: true },
  { id: 'cat-student-loans', name: 'Student Loans', type: 'liability', icon: 'academic', color: '#f87171', isDefault: true },
  { id: 'cat-mortgage', name: 'Mortgage', type: 'liability', icon: 'home', color: '#dc2626', isDefault: true },
  { id: 'cat-auto-loan', name: 'Auto Loan', type: 'liability', icon: 'car', color: '#fb923c', isDefault: true },
  { id: 'cat-personal-loan', name: 'Personal Loan', type: 'liability', icon: 'user', color: '#e11d48', isDefault: true },
  { id: 'cat-other-liabilities', name: 'Other Liabilities', type: 'liability', icon: 'box', color: '#9f1239', isDefault: true },
]

export function fullSeedState() {
  return {
    items: [...sampleAssets(), ...sampleLiabilities()],
    categories: DEFAULT_CATEGORIES,
    snapshots: sampleSnapshots(),
    baseCurrency: 'USD',
    exchangeRates: sampleExchangeRates(),
    theme: 'system',
    lastSnapshotDate: '2025-03-01',
    snapshotReminder: true,
  }
}
